import Head from "next/head";
import styles from "../styles/Home.module.css";
import { SortButton } from "../components/SortButton";
import { ShowTodoList } from "../components/ShowTodoList";
import { TodoForm } from "../components/TodoForm";

export default function Home() {
  const handleButtonDisabled = (todoArray: Todo[]) => {
    return todoArray.some((todo) => todo.edit);
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1>TODOリスト</h1>
        <TodoForm handleButtonDisabled={handleButtonDisabled} />
        <ul style={{ listStyle: "none" }}>
          <ShowTodoList handleButtonDisabled={handleButtonDisabled} />
        </ul>
        <div>
          <SortButton
            sortKey="fix"
            text="完了タスク一覧"
            handleDisabled={handleButtonDisabled}
          />
          <SortButton
            sortKey="notFix"
            text="未完了タスク一覧"
            handleDisabled={handleButtonDisabled}
          />
          <SortButton
            sortKey="all"
            text="すべてのタスク一覧"
            handleDisabled={handleButtonDisabled}
          />
        </div>
      </main>
    </div>
  );
}
