import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { v4 as uuidv4 } from "uuid";
import Link from "next/link";
import { SetStateAction, useEffect, useState } from "react";
import { LinkButton } from "./components/LinkButton";
import { ShowTodoList } from "./components/ShowTodoList";

export default function Home() {
  const [todo, setTodo] = useState("");
  const [todos, setTodos] = useState<Todo[]>([]);

  type Todo = {
    inputText: string;
    id: string;
    checked: boolean;
    edit: boolean;
  };

  const handleInputTodo = (e: {
    target: { value: SetStateAction<string> };
  }) => {
    setTodo(e.target.value);
  };

  const handleFormSubmit = (e: { preventDefault: () => void }) => {
    e.preventDefault();
    setTodos([
      { id: uuidv4(), inputText: todo.trim(), edit: false, checked: false },
      ...todos,
    ]);
    setTodo("");
    console.log(todos);
  };

  const handleDeleteTodo = (id: string) => {
    const newTodos = todos.filter((todo) => {
      if (todo.id !== id) {
        return todo;
      }
    });
    setTodos(newTodos);
  };

  const handleOnCheck = (id: string, checked: boolean) => {
    const newTodos = todos.map((todo) => {
      if (todo.id === id) {
        todo.checked = !checked;
      }
      return todo;
    });

    setTodos(newTodos);
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1>TODOリスト</h1>
        <form onSubmit={handleFormSubmit}>
          <input
            type="text"
            value={todo}
            name="todo"
            onChange={handleInputTodo}
          ></input>
          <button type="submit">タスク追加</button>
        </form>

        <ul style={{ listStyle: "none" }}>
          <ShowTodoList
            todoArray={todos}
            handleDeleteTodo={handleDeleteTodo}
            handleOnCheck={handleOnCheck}
          />
        </ul>

        <div>
          <LinkButton url="/completeTodo" text="完了タスク一覧" />
          <LinkButton url="/notCompleteTodo" text="未完了タスク一覧" />
        </div>
      </main>
    </div>
  );
}
